from __future__ import annotations

import os
import shlex
import stat
import sys
from dataclasses import dataclass
from pathlib import Path

from recallary.config import Settings


@dataclass(frozen=True)
class LauncherResult:
    path: Path
    log_path: Path
    python_path: Path


def _platform_log_path(settings: Settings, platform_name: str) -> Path:
    if platform_name.startswith("win"):
        return settings.logs_dir / "launcher-windows.log"
    if platform_name == "darwin":
        return settings.logs_dir / "launcher-macos.log"
    return settings.logs_dir / "launcher.log"


def _vbs_string(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def _windows_pythonw(python_executable: Path) -> Path:
    candidate = python_executable.with_name("pythonw.exe")
    return candidate if candidate.is_file() else python_executable


def _windows_conda_prefix(python_executable: Path) -> Path:
    if python_executable.parent.name.lower() == "scripts":
        return python_executable.parent.parent
    return python_executable.parent


def _write_windows_launcher(
    settings: Settings,
    python_executable: Path,
) -> LauncherResult:
    python_path = _windows_pythonw(python_executable)
    conda_prefix = _windows_conda_prefix(python_path)
    path_parts = [
        conda_prefix,
        conda_prefix / "Library" / "mingw-w64" / "bin",
        conda_prefix / "Library" / "usr" / "bin",
        conda_prefix / "Library" / "bin",
        conda_prefix / "Scripts",
        conda_prefix / "bin",
    ]
    path_prefix = ";".join(os.fspath(part) for part in path_parts)
    launcher_path = settings.root / "Recallary.vbs"
    log_path = _platform_log_path(settings, "win32")
    command = f'"{python_path}" -m recallary.launcher'
    content = "\n".join(
        [
            "' Auto-generated by `recallary make-launcher`.",
            "' Re-run that command if the Conda environment or repo path changes.",
            "Set shell = CreateObject(\"WScript.Shell\")",
            "Set env = shell.Environment(\"Process\")",
            f"env(\"CONDA_PREFIX\") = {_vbs_string(os.fspath(conda_prefix))}",
            f"env(\"CONDA_DEFAULT_ENV\") = {_vbs_string(conda_prefix.name)}",
            "env(\"PYTHONUTF8\") = \"1\"",
            f"env(\"PATH\") = {_vbs_string(path_prefix)} & \";\" & env(\"PATH\")",
            f"shell.CurrentDirectory = {_vbs_string(os.fspath(settings.root))}",
            f"shell.Run {_vbs_string(command)}, 0, False",
            "",
        ]
    )
    launcher_path.write_text(content, encoding="utf-8")
    return LauncherResult(
        path=launcher_path,
        log_path=log_path,
        python_path=python_path,
    )


def _write_macos_launcher(
    settings: Settings,
    python_executable: Path,
) -> LauncherResult:
    app_path = settings.root / "Recallary.app"
    contents_dir = app_path / "Contents"
    macos_dir = contents_dir / "MacOS"
    macos_dir.mkdir(parents=True, exist_ok=True)
    log_path = _platform_log_path(settings, "darwin")

    script_path = macos_dir / "Recallary"
    script = "\n".join(
        [
            "#!/bin/sh",
            "# Auto-generated by `recallary make-launcher`.",
            "# Re-run that command if the Conda environment or repo path changes.",
            f"export CONDA_PREFIX={shlex.quote(os.fspath(python_executable.parent.parent))}",
            f"export CONDA_DEFAULT_ENV={shlex.quote(python_executable.parent.parent.name)}",
            "export PYTHONUTF8=1",
            f"export PATH={shlex.quote(os.fspath(python_executable.parent.parent / 'bin'))}:$PATH",
            f"cd {shlex.quote(os.fspath(settings.root))} || exit 1",
            f"exec {shlex.quote(os.fspath(python_executable))} -m recallary.launcher",
            "",
        ]
    )
    script_path.write_text(script, encoding="utf-8")
    script_path.chmod(script_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    plist_path = contents_dir / "Info.plist"
    plist = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key>
  <string>Recallary</string>
  <key>CFBundleIdentifier</key>
  <string>local.recallary.launcher</string>
  <key>CFBundleName</key>
  <string>Recallary</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleVersion</key>
  <string>1</string>
  <key>LSMinimumSystemVersion</key>
  <string>11.0</string>
</dict>
</plist>
"""
    plist_path.write_text(plist, encoding="utf-8")
    return LauncherResult(
        path=app_path,
        log_path=log_path,
        python_path=python_executable,
    )


def make_launcher(
    settings: Settings,
    *,
    python_executable: Path | None = None,
    platform_name: str | None = None,
) -> LauncherResult:
    settings.configure_local_storage()
    active_python = (python_executable or Path(sys.executable)).resolve()
    active_platform = platform_name or sys.platform

    if active_platform.startswith("win"):
        return _write_windows_launcher(settings, active_python)
    if active_platform == "darwin":
        return _write_macos_launcher(settings, active_python)
    raise RuntimeError(
        f"Recallary launcher generation is only implemented for Windows and macOS. "
        f"Current platform: {active_platform}"
    )
